### ISSUE TITLE
Can't download script

### ISSUE THREAD

**Issue by nikillpop** [phpocean/How-to-create-a-simple-news-web-site#1]
Hello I can't download the script because I need to pay for a membership to download things so can you upload it to something like filezilla or MEGA so I can download the script please

**Comment by Thandohimself** [comment]
you won't get it from this dick head my friend

**Comment by zooboole** [comment]
Oh unfortunately I did not even see this message... wow that surprising. I hope you found a way then. I am really sorry @nikillpop
